# =========================================================
# 多模型API服务器配置文件
# =========================================================

# 服务器基本配置
# ---------------------------------------------------------
# port: 服务器监听端口
# debug_mode: 是否启用调试模式（true/false）
# debug_level: 调试信息详细程度（1-简单、2-详细、3-全部）
# admin_key: 管理API的访问密钥（用于更新API令牌）
server:
  port: 3000
  debug_mode: false
  debug_level: 2
  admin_key: "123456"  # 请修改为强密码

# Claude API配置
# ---------------------------------------------------------
# api_url: Claude API服务地址
# models: 支持的Claude模型列表，第一个为默认
# provider: API提供商
# api_key: 直接配置API密钥（优先使用，留空则使用文件）
# api_key_path: API密钥文件路径（当api_key为空时使用）
claude:
  api_url: "https://xxxxxx"
  models:a
    - "claude-3-7-sonnet-latest"
    - "claude-3-5-sonnet-latest"
  provider: "anthropic"
  api_key: ""  # 留空则使用api_key_path
  api_key_path: ""  # 当api_key为空时读取此文件

# DeepSeek API配置
# ---------------------------------------------------------
# api_domain: DeepSeek API域名
# user_agent: 请求使用的User-Agent
# timeout_ms: 请求超时时间（毫秒）
deepseek:
  api_domain: "xxxxxx"
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
  timeout_ms: 30000

# 模型列表配置
# ---------------------------------------------------------
# 用于/v1/models接口返回的模型列表
models:
  - id: "claude-3-7-sonnet-latest"
    object: "model"
    owned_by: "anthropic"
    description: "Claude 3.7 Sonnet - 最新版本的Claude模型"
  
  - id: "claude-3-5-sonnet-latest"
    object: "model"
    owned_by: "anthropic"
    description: "Claude 3.5 Sonnet - 性能与成本更平衡的Claude模型"
  
  - id: "deepseek-r1"
    object: "model"
    owned_by: "deepseek"
    description: "DeepSeek R1 模型（包含思考过程输出）"
  
  - id: "deepclaude"
    object: "model"
    owned_by: "hybrid"
    description: "DeepSeek思考过程 + Claude回答的混合模型"
    hybrid_config: {
      thinking_model: "deepseek-r1",
      answer_model: "claude-3-7-sonnet-latest"
    } 
